/* Generated by tools/gen_box.py (Unicode 16.0.0). Do not edit. */
#ifndef GLYPH_BOX_TABLE_H
#define GLYPH_BOX_TABLE_H

static const uint16_t box_table[128] = {
    0x0044, /* box drawings light horizontal */
    0x0088, /* box drawings heavy horizontal */
    0x0011, /* box drawings light vertical */
    0x0022, /* box drawings heavy vertical */
    0x0144, /* box drawings light triple dash horizontal */
    0x0188, /* box drawings heavy triple dash horizontal */
    0x0111, /* box drawings light triple dash vertical */
    0x0122, /* box drawings heavy triple dash vertical */
    0x0144, /* box drawings light quadruple dash horizontal */
    0x0188, /* box drawings heavy quadruple dash horizontal */
    0x0111, /* box drawings light quadruple dash vertical */
    0x0122, /* box drawings heavy quadruple dash vertical */
    0x0014, /* box drawings light down and right */
    0x0018, /* box drawings down light and right heavy */
    0x0024, /* box drawings down heavy and right light */
    0x0028, /* box drawings heavy down and right */
    0x0050, /* box drawings light down and left */
    0x0090, /* box drawings down light and left heavy */
    0x0060, /* box drawings down heavy and left light */
    0x00A0, /* box drawings heavy down and left */
    0x0005, /* box drawings light up and right */
    0x0009, /* box drawings up light and right heavy */
    0x0006, /* box drawings up heavy and right light */
    0x000A, /* box drawings heavy up and right */
    0x0041, /* box drawings light up and left */
    0x0081, /* box drawings up light and left heavy */
    0x0042, /* box drawings up heavy and left light */
    0x0082, /* box drawings heavy up and left */
    0x0015, /* box drawings light vertical and right */
    0x0019, /* box drawings vertical light and right heavy */
    0x0016, /* box drawings up heavy and right down light */
    0x0025, /* box drawings down heavy and right up light */
    0x0026, /* box drawings vertical heavy and right light */
    0x001A, /* box drawings down light and right up heavy */
    0x0029, /* box drawings up light and right down heavy */
    0x002A, /* box drawings heavy vertical and right */
    0x0051, /* box drawings light vertical and left */
    0x0091, /* box drawings vertical light and left heavy */
    0x0052, /* box drawings up heavy and left down light */
    0x0061, /* box drawings down heavy and left up light */
    0x0062, /* box drawings vertical heavy and left light */
    0x0092, /* box drawings down light and left up heavy */
    0x00A1, /* box drawings up light and left down heavy */
    0x00A2, /* box drawings heavy vertical and left */
    0x0054, /* box drawings light down and horizontal */
    0x0094, /* box drawings left heavy and right down light */
    0x0058, /* box drawings right heavy and left down light */
    0x0098, /* box drawings down light and horizontal heavy */
    0x0064, /* box drawings down heavy and horizontal light */
    0x00A4, /* box drawings right light and left down heavy */
    0x0068, /* box drawings left light and right down heavy */
    0x00A8, /* box drawings heavy down and horizontal */
    0x0045, /* box drawings light up and horizontal */
    0x0085, /* box drawings left heavy and right up light */
    0x0049, /* box drawings right heavy and left up light */
    0x0089, /* box drawings up light and horizontal heavy */
    0x0046, /* box drawings up heavy and horizontal light */
    0x0086, /* box drawings right light and left up heavy */
    0x004A, /* box drawings left light and right up heavy */
    0x008A, /* box drawings heavy up and horizontal */
    0x0055, /* box drawings light vertical and horizontal */
    0x0095, /* box drawings left heavy and right vertical light */
    0x0059, /* box drawings right heavy and left vertical light */
    0x0099, /* box drawings vertical light and horizontal heavy */
    0x0056, /* box drawings up heavy and down horizontal light */
    0x0065, /* box drawings down heavy and up horizontal light */
    0x0066, /* box drawings vertical heavy and horizontal light */
    0x0096, /* box drawings left up heavy and right down light */
    0x005A, /* box drawings right up heavy and left down light */
    0x00A5, /* box drawings left down heavy and right up light */
    0x0069, /* box drawings right down heavy and left up light */
    0x009A, /* box drawings down light and up horizontal heavy */
    0x00A9, /* box drawings up light and down horizontal heavy */
    0x00A6, /* box drawings right light and left vertical heavy */
    0x006A, /* box drawings left light and right vertical heavy */
    0x00AA, /* box drawings heavy vertical and horizontal */
    0x0144, /* box drawings light double dash horizontal */
    0x0188, /* box drawings heavy double dash horizontal */
    0x0111, /* box drawings light double dash vertical */
    0x0122, /* box drawings heavy double dash vertical */
    0x00CC, /* box drawings double horizontal */
    0x0033, /* box drawings double vertical */
    0x001C, /* box drawings down single and right double */
    0x0034, /* box drawings down double and right single */
    0x003C, /* box drawings double down and right */
    0x00D0, /* box drawings down single and left double */
    0x0070, /* box drawings down double and left single */
    0x00F0, /* box drawings double down and left */
    0x000D, /* box drawings up single and right double */
    0x0007, /* box drawings up double and right single */
    0x000F, /* box drawings double up and right */
    0x00C1, /* box drawings up single and left double */
    0x0043, /* box drawings up double and left single */
    0x00C3, /* box drawings double up and left */
    0x001D, /* box drawings vertical single and right double */
    0x0037, /* box drawings vertical double and right single */
    0x003F, /* box drawings double vertical and right */
    0x00D1, /* box drawings vertical single and left double */
    0x0073, /* box drawings vertical double and left single */
    0x00F3, /* box drawings double vertical and left */
    0x00DC, /* box drawings down single and horizontal double */
    0x0074, /* box drawings down double and horizontal single */
    0x00FC, /* box drawings double down and horizontal */
    0x00CD, /* box drawings up single and horizontal double */
    0x0047, /* box drawings up double and horizontal single */
    0x00CF, /* box drawings double up and horizontal */
    0x00DD, /* box drawings vertical single and horizontal double */
    0x0077, /* box drawings vertical double and horizontal single */
    0x00FF, /* box drawings double vertical and horizontal */
    0x0214, /* box drawings light arc down and right */
    0x0250, /* box drawings light arc down and left */
    0x0241, /* box drawings light arc up and left */
    0x0205, /* box drawings light arc up and right */
    0x0400, /* box drawings light diagonal upper right to lower left */
    0x0800, /* box drawings light diagonal upper left to lower right */
    0x0C00, /* box drawings light diagonal cross */
    0x0040, /* box drawings light left */
    0x0001, /* box drawings light up */
    0x0004, /* box drawings light right */
    0x0010, /* box drawings light down */
    0x0080, /* box drawings heavy left */
    0x0002, /* box drawings heavy up */
    0x0008, /* box drawings heavy right */
    0x0020, /* box drawings heavy down */
    0x0048, /* box drawings light left and heavy right */
    0x0021, /* box drawings light up and heavy down */
    0x0084, /* box drawings heavy left and light right */
    0x0012, /* box drawings heavy up and light down */
};

#endif
