#!/usr/bin/env python3
"""Generates swift/Sources/FosforoSSH/BlowfishTables.swift.

Blowfish's initial P-array and S-boxes are, by definition, the hexadecimal
digits of pi's fractional part (P first, then S0..S3): 1042 32-bit words.
Computed here with Machin's formula in integer arithmetic instead of pasted.

Usage: python3 tools/gen_blowfish.py > swift/Sources/FosforoSSH/BlowfishTables.swift
"""
import sys

WORDS = 18 + 4 * 256
BITS = WORDS * 32 + 64  # guard bits against rounding in the last word


def arctan_inv(x, one):
    # arctan(1/x) * one, by its Taylor series
    total = term = one // x
    x2 = x * x
    n = 1
    sign = -1
    while term:
        term //= x2
        total += sign * (term // (2 * n + 1))
        sign = -sign
        n += 1
    return total


one = 1 << BITS
pi = 4 * (4 * arctan_inv(5, one) - arctan_inv(239, one))
frac = pi - (3 << BITS)
words = [(frac >> (BITS - 32 * (i + 1))) & 0xFFFFFFFF for i in range(WORDS)]
assert words[0] == 0x243F6A88 and words[17] == 0x8979FB1B and words[18] == 0xD1310BA6

out = sys.stdout
out.write("// Generated by tools/gen_blowfish.py: hex digits of pi. Do not edit.\n\n")
out.write("let blowfishP: [UInt32] = [\n")
for i in range(0, 18, 6):
    out.write("  " + ", ".join("0x%08X" % w for w in words[i:i + 6]) + ",\n")
out.write("]\n\nlet blowfishS: [[UInt32]] = [\n")
for box in range(4):
    base = 18 + box * 256
    out.write("  [\n")
    for i in range(0, 256, 6):
        out.write("    " + ", ".join("0x%08X" % w for w in words[base + i:base + min(i + 6, 256)]) + ",\n")
    out.write("  ],\n")
out.write("]\n")
