#!/usr/bin/env python3
"""Generates glyph/box_table.h: the arms of each box drawing rune U+2500..257F.

Each entry packs four 2-bit weights (up, right, down, left: 0 none, 1 light,
2 heavy, 3 double) in the low byte, plus BOX_DASH, BOX_ARC and the diagonal
bits. Parsed from the Unicode character names, so the table cannot drift from
the standard by a typo.

Usage: python3 tools/gen_box.py > glyph/box_table.h
"""
import sys
import unicodedata

WEIGHT = {"LIGHT": 1, "SINGLE": 1, "HEAVY": 2, "DOUBLE": 3}
DIRS = {"UP": [0], "RIGHT": [1], "DOWN": [2], "LEFT": [3],
        "VERTICAL": [0, 2], "HORIZONTAL": [1, 3]}
DASH, ARC, DIAG_RISING, DIAG_FALLING = 1 << 8, 1 << 9, 1 << 10, 1 << 11


def parse(name):
    words = name.removeprefix("BOX DRAWINGS ").split()
    flags = 0
    if "DIAGONAL" in words:
        if "CROSS" in words:
            return DIAG_RISING | DIAG_FALLING
        if words[words.index("DIAGONAL") + 1] == "UPPER" and "RIGHT" in words[:6]:
            return DIAG_RISING
        return DIAG_FALLING
    if "DASH" in words:
        i = words.index("DASH")
        del words[i - 1:i + 1]
        flags |= DASH
    if "ARC" in words:
        words.remove("ARC")
        flags |= ARC
    arms = [0, 0, 0, 0]
    weight = 0
    for group in " ".join(words).split(" AND "):
        dirs = []
        gw = 0
        for w in group.split():
            if w in WEIGHT:
                gw = WEIGHT[w]
            elif w in DIRS:
                dirs += DIRS[w]
            else:
                raise SystemExit("unknown word %r in %r" % (w, name))
        if gw:
            weight = gw
        for d in dirs:
            arms[d] = weight
    return flags | arms[0] | arms[1] << 2 | arms[2] << 4 | arms[3] << 6


out = sys.stdout
out.write("/* Generated by tools/gen_box.py (Unicode %s). Do not edit. */\n"
          % unicodedata.unidata_version)
out.write("#ifndef GLYPH_BOX_TABLE_H\n#define GLYPH_BOX_TABLE_H\n\n")
out.write("static const uint16_t box_table[128] = {\n")
for cp in range(0x2500, 0x2580):
    out.write("    0x%04X, /* %s */\n" % (parse(unicodedata.name(chr(cp))), unicodedata.name(chr(cp)).lower()))
out.write("};\n\n#endif\n")
