#!/usr/bin/env python3
"""Generates vt/compose_table.h: base + combining mark -> precomposed rune.

macOS hands out file names in NFD, so `ls` prints "c" + U+0327 where the
user wrote "ç". Without composition the mark would be dropped and the name
shown as "c". One canonical decomposition level is enough: stacked marks
(Vietnamese) compose step by step through the intermediate rune.

Usage: python3 tools/gen_compose.py > vt/compose_table.h
"""
import sys
import unicodedata

RANGES = [(0x00C0, 0x024F), (0x1E00, 0x1EFF)]

pairs = []
for lo, hi in RANGES:
    for cp in range(lo, hi + 1):
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        if len(parts) != 2:
            continue
        pairs.append((parts[0], parts[1], cp))

pairs.sort()
out = sys.stdout
out.write("/* Generated by tools/gen_compose.py (Unicode %s). Do not edit. */\n"
          % unicodedata.unidata_version)
out.write("#ifndef VT_COMPOSE_TABLE_H\n#define VT_COMPOSE_TABLE_H\n\n")
out.write("static const struct {\n    uint32_t base;\n    uint32_t mark;\n"
          "    uint32_t composed;\n} compose_table[] = {\n")
for base, mark, cp in pairs:
    out.write("    {0x%04X, 0x%04X, 0x%04X},\n" % (base, mark, cp))
out.write("};\n\n#endif\n")
