#!/bin/sh
# Generates swift/Sources/FosforoRender/Credits.swift from assets/licenses/:
# the notices third-party pieces require the app to reproduce, compiled in
# so every build carries them.
# usage: tools/gen_credits.sh > swift/Sources/FosforoRender/Credits.swift
set -eu

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    echo "usage: tools/gen_credits.sh > swift/Sources/FosforoRender/Credits.swift"
    echo "Embeds assets/licenses/*.txt as the app's credits text."
    exit 0
fi

echo '// Generated by tools/gen_credits.sh from assets/licenses. Do not edit.'
echo ''
echo '/// Third-party notices the app must show (About on the Mac, `credits`'
echo '/// in the launcher).'
echo 'public enum Credits {'
echo '  public static let text = #"""'
echo '    fosforo — MIT License, Copyright (c) 2026 Cesar Gimenes'
echo ''
for f in assets/licenses/*.txt; do
    name=$(basename "$f" .txt)
    echo "    The $name font:"
    echo ''
    sed 's/^/    /; s/[[:space:]]*$//' "$f"
    echo ''
done
echo '    """#'
echo '}'
