#!/usr/bin/env python3
"""Generates vt/cp437_table.h: bytes 0x80..0xFF of IBM code page 437.

Usage: python3 tools/gen_cp437.py > vt/cp437_table.h
"""
import sys

out = sys.stdout
out.write("/* Generated by tools/gen_cp437.py. Do not edit. */\n")
out.write("#ifndef VT_CP437_TABLE_H\n#define VT_CP437_TABLE_H\n\n")
out.write("static const uint16_t cp437_high[128] = {\n")
chars = bytes(range(0x80, 0x100)).decode("cp437")
for i in range(0, 128, 8):
    out.write("    " + ", ".join("0x%04X" % ord(c) for c in chars[i:i + 8]) + ",\n")
out.write("};\n\n#endif\n")
